name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v5
      with:
          context: ./apps/micro-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/micro-app
          file: ./apps/micro-app/Dockerfile

