name: Docker Image CI

on:
  push:
    branches: [ "dev/*" ]
  pull_request:
    branches: [ "dev/*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract App Name from Branch
      id: extract
      run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          APP_NAME=${BRANCH_NAME##*/}
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v5
      with:
          context: ./apps/micro-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract.outputs.app_name }}
          file: ./apps/micro-app/Dockerfile

